package org.wso2.siddhi.core.query.processor.filter;

import org.wso2.siddhi.core.event.ComplexEvent;

import java.lang.reflect.InvocationTargetException;

/**
 * Interface for the class generated by bytecode
 */
public interface AbstractOptimizedExpressionExecutor {
    /**
     * Abstract method to execute byte code.
     *
     * @param complexEvent
     * @return
     * @throws IllegalAccessException
     * @throws InstantiationException
     * @throws InvocationTargetException
     */
    public boolean optimizedExecuteWithByteCode(ComplexEvent complexEvent) throws IllegalAccessException,
            InstantiationException, InvocationTargetException;
}
