package org.wso2.siddhi.core.query.processor.filter;

/**
 * This is the ClassLoader for the class generated by byte code.
 */
public class OptimizedExpressionExecutorClassLoader extends ClassLoader {

    /**
     * This is an overridden method.
     *
     * @param name
     * @param b
     * @return
     */
    public Class defineClass(String name, byte[] b) {
        return defineClass(name, b, 0, b.length);
    }
}
